### PR TITLE
PR for bumping to latest Spark and Scala

### PR DESCRIPTION
**Pull request by bigsnarfdude**
Issue was created and this pull request includes changes to address Issue #1 
https://github.com/snowplow/spark-example-project/issues/1

### CODE REVIEW

**Comment by alexanderdean** [comment]
Many thanks @bigsnarfdude ! Two things:

1. Can you bump the Scala version in .travis.yml too so that tests pass
2. Can you sign our CLA please - https://github.com/snowplow/snowplow/wiki/CLA

Awesome to get this updated to Spark 1.0.0 - huge thanks for the contribution!!

**Comment by bigsnarfdude** [comment]
Signed

**Comment by alexanderdean** [comment]
Confirmed signature! Thanks, releasing now...

**Comment by alexanderdean** [comment]
Hey @bigsnarfdude - can you clarify what scripts/install-spark-shark.sh is for? The README is still using an old version hosted by AWS... Also there are lots of commented-out lines in scripts/install-spark-shark.sh - could you remove them if they're not needed?

**Comment by bigsnarfdude** [comment]
The script is a custom bootstrap for a hand rolled EMR Spark 1.0.0 that I found in another repo. http://s3.amazonaws.com/intentmedia-spark/setting-up-emr-spark-jar-instructions.txt 

I've been trying to figure out how to get the AWS Labs bootstrap code to work with your code. https://github.com/awslabs/emr-bootstrap-actions/tree/master/spark. 

The steps fail after the bootstrap file is completed. Something has changed from 0.8.1/0.9.3 Spark EMR to the 1.0.0/1.2.0 Spark EMR releases.

**Comment by alexanderdean** [comment]
Okay cool - so it sounds like we need the custom bootstrap?

**Comment by bigsnarfdude** [comment]
It looks like few things. 1. Custom hand rolled EMR image for 1.0.0. 2. Bootstrap script to finish the build and setup of the EMR/EC2 instances

I'm gonna keep hammering away at the custom build vs. AWS Labs build and test some different scenarios. I've familiarized myself with the bootstrap process now and just working thru the diffs on different builds to get see where the failure is. (No logs get generated on the bootstrap failures).

**Comment by alexanderdean** [comment]
Okay sounds good!

**Comment by bigsnarfdude** [comment]
Here are the gists of the Steps failure logs with a standard AWS Labs Bootstrap for 1.0.0. Cluster comes up and it looks like it loads jars to all nodes. Then 'maybe' it fails at main following the runner script?

https://gist.github.com/bigsnarfdude/b23c03b7133bfa170fc7
https://gist.github.com/bigsnarfdude/c762963f79f2da3cfd6a

**Comment by alexanderdean** [comment]
If `jarOfObject` can't be found, does that imply the wrong version of Spark is on the classpath?

**Comment by bigsnarfdude** [comment]
On 0.8.1 EMR and custom rolled 1.0.0 that work the classpath is https://gist.github.com/bigsnarfdude/0af238313cef824d329e.

Even on AWS Labs 1.0.0 EMR the classpath appears identical to the above gist. My next hunch is that something between the hadoop1 bin and hadoop2 bin.

**Comment by bigsnarfdude** [comment]
In keeping with your comment about the Spark Classpath..

In the wordcount.execute function (see gist below) I modified the object:anyref to a list, and maybe thats where the AWS Labs EMR barfs (type issue?).  I'm more inclined to getting the AWS EMR sorted out with your code, vs. continuing down the custom EMR path. (custom EMR building rabbit hole). 

I've got a sub comments going: https://gist.github.com/bigsnarfdude/0af238313cef824d329e

**Comment by alexanderdean** [comment]
I hear you! Good luck with it...

**Comment by alexanderdean** [comment]
Hey @bigsnarfdude - I am taking another look at this PR. My gut feel is that given the ongoing difficulties of running Spark on EMR, we should probably stop worrying about that option and instead add explanations of how to:

1. Run on "raw" EC2 using https://spark.apache.org/docs/latest/ec2-scripts.html
2. Run on Databricks Cloud using https://github.com/databricks/sbt-databricks

What do you reckon?

**Comment by bigsnarfdude** [comment]
Getting Spark EMR to work with AWS native AMI is something that we should be able to work through with time and effort. Working on it as a side project is definitely hampering its forward momentum to "master". I think that this will definitely have to be solved before moving on with data peek/pull integrations to S3, Kinesis, or Kafka.

**Comment by bigsnarfdude** [comment]
Databricks Cloud looks interesting. Managing your cluster with EC2 isn't very pain free.  EMR continues to be a promising option. Which leads me to another question...how do you manage job scheduling using EMR?.

**Comment by alexanderdean** [comment]
Snowplow's scheduling of Scalding jobs is done using @rslifka's excellent [Elasticity](https://github.com/rslifka/elasticity/) library, which we embed into our own [EmrEtlRunner](https://github.com/snowplow/snowplow/tree/master/3-enrich/emr-etl-runner).

I agree EMR is a nice abstraction over raw EC2 - I've created a ticket to add it back in: #8. In the meantime, I'll get an 0.3.0 out with the latest Spark version ASAP to unblock the team.

**Comment by bigsnarfdude** [comment]
Spark 1.3.0 (1.3.0.d) with EMR AMI 3.5.x and later?
--ami-version 3.6 --

**Comment by alexanderdean** [comment]
I will give it a go @bigsnarfdude !

**Comment by alexanderdean** [comment]
This is merged @bigsnarfdude ! Thanks for all your help on this.

**Pull request closed without merging**
